# Generated by Django 4.2.2 on 2023-07-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('muscle', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Routines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(null=True)),
                ('rest_duration', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('weight', models.IntegerField(null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.exercises')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness_app.routines')),
            ],
        ),
    ]
